config-version: 2

name: 'apple_search_ads_source_integration_tests'
version: '0.5.0'

profile: 'integration_tests' 

vars:
  apple_search_ads_schema: apple_ads_source_integrations_tests_1
  apple_search_ads_organization_identifier: "organization_data"
  apple_search_ads_campaign_history_identifier: "campaign_history_data"
  apple_search_ads_campaign_report_identifier: "campaign_report_data"
  apple_search_ads_ad_group_history_identifier: "ad_group_history_data"
  apple_search_ads_ad_group_report_identifier: "ad_group_report_data"
  apple_search_ads_ad_history_identifier: "ad_history_data"
  apple_search_ads_ad_level_report_identifier: "ad_report_data"
  apple_search_ads_keyword_history_identifier: "keyword_history_data"
  apple_search_ads_keyword_report_identifier: "keyword_report_data"
  apple_search_ads_search_term_report_identifier: "search_term_report_data"
  apple_search_ads__using_search_terms: True

  apple_search_ads__ad_group_passthrough_metrics:
    - name: conversions
    - name: lat_off_installs
  apple_search_ads__ad_passthrough_metrics:
    - name: conversions
      alias: conversions_alias_should_be_included

models:
  +schema: apple_search_ads_source

seeds:
  +quote_columns: "{{ true if target.type == 'redshift' else false }}"
  apple_search_ads_source_integration_tests:
    +column_types:
      modification_time: "timestamp"
      start_time: "timestamp"
      end_time: "timestamp"
      creation_time: "timestamp"
        
dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']
